baseURL = 'http://localhost:8080/'
locale = 'en-us'
title = "Matthew's Cookbook"
theme = "cookbook-theme"

[permalinks]
    recipe = "/recipes/:contentbasename/"

[params]  
    stylesheet = "/style.css"